version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - pytest --html=report.html --self-contained-html
      - ls -la report.html

artifacts:
  files:
    - report.html